# syntax=docker/dockerfile:1

# - - - - - - - - - - - - - - - - - - - - - - -
# - Titre : Z test
# - OS Version : Ubuntu 20.04
# - Fichier : Dockerfile_Z_test
# - - - - - - - - - - - - - - - - - - - - - - -

# Métadonnées de l'image
# LABEL os_version="Ubuntu 20.04"
# LABEL version="1.0.0"
# LABEL file="Dockerfile_Z_test"
# LABEL maintainer="vdumay <hello@ldumay.fr>"
# LABEL website="https://ldumay.fr"
# LABEL mail="hello@ldumay.fr"
# LABEL description="Test d'Ubuntu Focal Pack 2"
# MAINTAINER ldumay

# OS de base : Ubuntu Focal 20.04 20240416
FROM ldumay/ubuntu_focal_pack_2:1.0.0