# syntax=docker/dockerfile:1

# - - - - - - - - - - - - - - - - - - - - - - -
# - Titre : Ubuntu Focal Pack 1
# - OS Version : Ubuntu 20.04
# - Fichier : Dockerfile_UbuntuFocal_Pack_1
# - - - - - - - - - - - - - - - - - - - - - - -

# Métadonnées de l'image
# LABEL os_version="Ubuntu 20.04"
# LABEL version="1.0.0"
# LABEL file="Dockerfile_UbuntuFocal_Pack_1"
# LABEL maintainer="vdumay <hello@ldumay.fr>"
# LABEL website="https://ldumay.fr"
# LABEL mail="hello@ldumay.fr"
# LABEL description="Ubuntu Focal Pack 1\
# 	Ceci est une image d'Ubuntu Focal 20.04 avec des paquets simple."
# MAINTAINER ldumay

# OS de base : Ubuntu Focal 20.04 20240416
FROM ubuntu:focal-20240416

# Mise à jour et mise à niveau du noyaux du conteneur
RUN apt-get upgrade && apt-get update && apt-get clean

# Installation des paquets de bases
RUN apt-get -y install vim nano tree curl wget net-tools